/*
 * Dybov's and Lavrov's SoA lab-1
 * Some dragons service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {Country} from './Country.js';
import {Person} from './Person.js';

/**
 * The AllOfDragonKiller model module.
 * @module model/AllOfDragonKiller
 * @version 1.0.0
 */
export class AllOfDragonKiller extends Person {
  /**
   * Constructs a new <code>AllOfDragonKiller</code>.
   * @alias module:model/AllOfDragonKiller
   * @class
   * @extends module:model/Person
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>AllOfDragonKiller</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfDragonKiller} obj Optional instance to populate.
   * @return {module:model/AllOfDragonKiller} The populated <code>AllOfDragonKiller</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfDragonKiller();
      Person.constructFromObject(data, obj);
    }
    return obj;
  }
}
