/*
 * Dybov's and Lavrov's SoA lab-1
 * Some dragons service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * Enum class Color.
 * @enum {String}
 * @readonly
 */
const Color = {
  /**
   * value: "RED"
   * @const
   */
  RED: "RED",

  /**
   * value: "YELLOW"
   * @const
   */
  YELLOW: "YELLOW",

  /**
   * value: "ORANGE"
   * @const
   */
  ORANGE: "ORANGE",

  /**
   * value: "BROWN"
   * @const
   */
  BROWN: "BROWN",

  /**
   * Returns a <code>Color</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/Color} The enum <code>Color</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {Color};