/*
 * Dybov's and Lavrov's SoA lab-1
 * Some dragons service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The Coordinates model module.
 * @module model/Coordinates
 * @version 1.0.0
 */
export class Coordinates {
  /**
   * Constructs a new <code>Coordinates</code>.
   * @alias module:model/Coordinates
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Coordinates</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Coordinates} obj Optional instance to populate.
   * @return {module:model/Coordinates} The populated <code>Coordinates</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Coordinates();
      if (data.hasOwnProperty('x'))
        obj.x = ApiClient.convertToType(data['x'], 'Number');
      if (data.hasOwnProperty('y'))
        obj.y = ApiClient.convertToType(data['y'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} x
 */
Coordinates.prototype.x = undefined;

/**
 * @member {Number} y
 */
Coordinates.prototype.y = undefined;

