/*
 * Dybov's and Lavrov's SoA lab-1
 * Some dragons service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * Enum class Country.
 * @enum {String}
 * @readonly
 */
const Country = {
  /**
   * value: "FRANCE"
   * @const
   */
  FRANCE: "FRANCE",

  /**
   * value: "SPAIN"
   * @const
   */
  SPAIN: "SPAIN",

  /**
   * value: "CHINA"
   * @const
   */
  CHINA: "CHINA",

  /**
   * Returns a <code>Country</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/Country} The enum <code>Country</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {Country};