/*
 * Dybov's and Lavrov's SoA lab-1
 * Some dragons service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * Enum class DragonCharacter.
 * @enum {String}
 * @readonly
 */
const DragonCharacter = {
  /**
   * value: "CUNNING"
   * @const
   */
  CUNNING: "CUNNING",

  /**
   * value: "WISE"
   * @const
   */
  WISE: "WISE",

  /**
   * value: "EVIL"
   * @const
   */
  EVIL: "EVIL",

  /**
   * value: "CHAOTIC,"
   * @const
   */
  CHAOTIC: "CHAOTIC,",

  /**
   * value: "CHAOTIC_EVIL"
   * @const
   */
  CHAOTIC_EVIL: "CHAOTIC_EVIL",

  /**
   * Returns a <code>DragonCharacter</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DragonCharacter} The enum <code>DragonCharacter</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {DragonCharacter};