/*
 * Dybov's and Lavrov's SoA lab-1
 * Some dragons service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * Enum class DragonType.
 * @enum {String}
 * @readonly
 */
const DragonType = {
  /**
   * value: "WATER"
   * @const
   */
  WATER: "WATER",

  /**
   * value: "UNDERGROUND"
   * @const
   */
  UNDERGROUND: "UNDERGROUND",

  /**
   * value: "AIR"
   * @const
   */
  AIR: "AIR",

  /**
   * value: "FIRE"
   * @const
   */
  FIRE: "FIRE",

  /**
   * Returns a <code>DragonType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DragonType} The enum <code>DragonType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {DragonType};