/*
 * Dybov's and Lavrov's SoA lab-1
 * Some dragons service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {Color} from './Color.js';
import {Coordinates} from './Coordinates.js';
import {DragonCharacter} from './DragonCharacter.js';
import {DragonType} from './DragonType.js';

/**
 * The Dragon model module.
 * @module model/Dragon
 * @version 1.0.0
 */
export class Dragon {
  /**
   * Constructs a new <code>Dragon</code>.
   * @alias module:model/Dragon
   * @class
   * @param name {String} 
   * @param coordinates {module:model/Coordinates} 
   * @param type {module:model/DragonType} 
   */
  constructor(name, coordinates, type) {
    this.name = name;
    this.coordinates = coordinates;
    this.type = type;
  }

  /**
   * Constructs a <code>Dragon</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Dragon} obj Optional instance to populate.
   * @return {module:model/Dragon} The populated <code>Dragon</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Dragon();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('coordinates'))
        obj.coordinates = Coordinates.constructFromObject(data['coordinates']);
      if (data.hasOwnProperty('creationDate'))
        obj.creationDate = ApiClient.convertToType(data['creationDate'], 'Date');
      if (data.hasOwnProperty('age'))
        obj.age = ApiClient.convertToType(data['age'], 'Number');
      if (data.hasOwnProperty('color'))
        obj.color = Color.constructFromObject(data['color']);
      if (data.hasOwnProperty('character'))
        obj.character = DragonCharacter.constructFromObject(data['character']);
      if (data.hasOwnProperty('type'))
        obj.type = DragonType.constructFromObject(data['type']);
      if (data.hasOwnProperty('killer'))
        obj.killer = ApiClient.convertToType(data['killer'], Object);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Dragon.prototype.id = undefined;

/**
 * @member {String} name
 */
Dragon.prototype.name = undefined;

/**
 * @member {module:model/Coordinates} coordinates
 */
Dragon.prototype.coordinates = undefined;

/**
 * @member {Date} creationDate
 */
Dragon.prototype.creationDate = undefined;

/**
 * @member {Number} age
 */
Dragon.prototype.age = undefined;

/**
 * @member {module:model/Color} color
 */
Dragon.prototype.color = undefined;

/**
 * @member {module:model/DragonCharacter} character
 */
Dragon.prototype.character = undefined;

/**
 * @member {module:model/DragonType} type
 */
Dragon.prototype.type = undefined;

/**
 * @member {Object} killer
 */
Dragon.prototype.killer = undefined;

