//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.02 at 11:08:57 PM MSK 
//


package ru.ifmo.soa.dragons.api.schema;

import lombok.*;
import ru.ifmo.soa.persons.api.schema.PersonResponse;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.time.LocalDate;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DragonResponse", propOrder = {
    "id",
    "name",
    "creationDate",
    "coordinates",
    "age",
    "color",
    "type",
    "character",
        "killer"
})
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@XmlRootElement(name="dragonResponse", namespace = "http://ru/ifmo/soa/")
public class DragonResponse {

    protected long id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected LocalDate creationDate;
    @XmlElement(required = true)
    protected CoordinatesResponse coordinates;
    protected int age;
    @XmlElement(required = true)
    protected String color;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String character;
    @XmlElement(nillable = true)
    protected PersonResponse killer;


}
