/*
 * Dybov's and Lavrov's SoA lab-1
 * Some dragons service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient.js';
import {AllOfDragonKiller} from './model/AllOfDragonKiller.js';
import {Color} from './model/Color.js';
import {Coordinates} from './model/Coordinates.js';
import {Country} from './model/Country.js';
import {Dragon} from './model/Dragon.js';
import {DragonCharacter} from './model/DragonCharacter.js';
import {DragonType} from './model/DragonType.js';
import {Filter} from './model/Filter.js';
import {Person} from './model/Person.js';
import {Sort} from './model/Sort.js';
import {CRUDApi} from './api/CRUDApi.js';
import {KillerApi} from './api/KillerApi.js';

/**
* Some_dragons_service.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DybovsAndLavrovsSoALab1 = require('index'); // See note below*.
* var xxxSvc = new DybovsAndLavrovsSoALab1.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DybovsAndLavrovsSoALab1.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue.js';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DybovsAndLavrovsSoALab1.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DybovsAndLavrovsSoALab1.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue.js';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AllOfDragonKiller model constructor.
     * @property {module:model/AllOfDragonKiller}
     */
    AllOfDragonKiller,

    /**
     * The Color model constructor.
     * @property {module:model/Color}
     */
    Color,

    /**
     * The Coordinates model constructor.
     * @property {module:model/Coordinates}
     */
    Coordinates,

    /**
     * The Country model constructor.
     * @property {module:model/Country}
     */
    Country,

    /**
     * The Dragon model constructor.
     * @property {module:model/Dragon}
     */
    Dragon,

    /**
     * The DragonCharacter model constructor.
     * @property {module:model/DragonCharacter}
     */
    DragonCharacter,

    /**
     * The DragonType model constructor.
     * @property {module:model/DragonType}
     */
    DragonType,

    /**
     * The Filter model constructor.
     * @property {module:model/Filter}
     */
    Filter,

    /**
     * The Person model constructor.
     * @property {module:model/Person}
     */
    Person,

    /**
     * The Sort model constructor.
     * @property {module:model/Sort}
     */
    Sort,

    /**
    * The CRUDApi service constructor.
    * @property {module:api/CRUDApi}
    */
    CRUDApi,

    /**
    * The KillerApi service constructor.
    * @property {module:api/KillerApi}
    */
    KillerApi
};
