//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.02 at 11:08:57 PM MSK 
//


package ru.ifmo.soa.persons.api.schema;

import lombok.*;

import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@XmlRootElement(name="deletePersonRequest", namespace = "http://ru/ifmo/soa/")
public class DeletePersonRequest {

    @XmlElement(required = true)
    private String passportID;



}
